using FinanSmart.Api.Common.Exceptions;using FinanSmart.Api.Data.Context;using FinanSmart.Api.Entities;using FinanSmart.Api.Modules.Investments.Rates.DTOs;using FinanSmart.Api.Modules.Investments.Rates.Interfaces;using Microsoft.EntityFrameworkCore;
namespace FinanSmart.Api.Modules.Investments.Rates.Services;
public class InvestmentRateService(FinanSmartDbContext db):IInvestmentRateService
{
 public async Task<IReadOnlyCollection<InvestmentRateDto>> GetAllAsync()=>await db.InvestmentRates.AsNoTracking().Include(x=>x.InvestmentProduct).OrderBy(x=>x.InvestmentProduct.Name).ThenByDescending(x=>x.EffectiveFrom).Select(x=>Map(x)).ToListAsync();
 public async Task<InvestmentRateDto?> GetByIdAsync(Guid id){var x=await db.InvestmentRates.AsNoTracking().Include(x=>x.InvestmentProduct).FirstOrDefaultAsync(x=>x.Id==id);return x is null?null:Map(x);}
 public async Task<IReadOnlyCollection<InvestmentRateDto>> GetByProductAsync(Guid id)=>await db.InvestmentRates.AsNoTracking().Include(x=>x.InvestmentProduct).Where(x=>x.InvestmentProductId==id).OrderByDescending(x=>x.EffectiveFrom).Select(x=>Map(x)).ToListAsync();
 public async Task<InvestmentRateDto?> GetApplicableRateAsync(Guid productId,decimal amount,int termDays){var now=DateTimeOffset.UtcNow;var x=await db.InvestmentRates.AsNoTracking().Include(x=>x.InvestmentProduct).FirstOrDefaultAsync(x=>x.InvestmentProductId==productId&&x.IsActive&&(x.MinimumAmount==null||x.MinimumAmount<=amount)&&(x.MaximumAmount==null||x.MaximumAmount>=amount)&&(x.MinimumTermDays==null||x.MinimumTermDays<=termDays)&&(x.MaximumTermDays==null||x.MaximumTermDays>=termDays)&&x.EffectiveFrom<=now&&(x.EffectiveTo==null||x.EffectiveTo>=now));return x is null?null:Map(x);}
 public async Task<InvestmentRateDto> CreateAsync(CreateInvestmentRateDto dto){Validate(dto.MinimumAmount,dto.MaximumAmount,dto.MinimumTermDays,dto.MaximumTermDays,dto.AnnualInterestRate,dto.EffectiveFrom,dto.EffectiveTo);await EnsureProduct(dto.InvestmentProductId,true);if(dto.IsActive&&await Overlaps(dto.InvestmentProductId,dto.MinimumAmount,dto.MaximumAmount,dto.MinimumTermDays,dto.MaximumTermDays,dto.EffectiveFrom,dto.EffectiveTo,null))throw new InvestmentRateOverlapException();var now=DateTimeOffset.UtcNow;var x=new InvestmentRate{Id=Guid.NewGuid(),InvestmentProductId=dto.InvestmentProductId,MinimumAmount=dto.MinimumAmount,MaximumAmount=dto.MaximumAmount,MinimumTermDays=dto.MinimumTermDays,MaximumTermDays=dto.MaximumTermDays,AnnualInterestRate=dto.AnnualInterestRate,EffectiveFrom=dto.EffectiveFrom,EffectiveTo=dto.EffectiveTo,IsActive=dto.IsActive,CreatedAt=now,UpdatedAt=now};db.InvestmentRates.Add(x);await db.SaveChangesAsync();await db.Entry(x).Reference(x=>x.InvestmentProduct).LoadAsync();return Map(x);}
 public async Task<bool> UpdateAsync(Guid id,UpdateInvestmentRateDto dto){Validate(dto.MinimumAmount,dto.MaximumAmount,dto.MinimumTermDays,dto.MaximumTermDays,dto.AnnualInterestRate,dto.EffectiveFrom,dto.EffectiveTo);var x=await db.InvestmentRates.FindAsync(id);if(x is null)return false;await EnsureProduct(dto.InvestmentProductId,x.InvestmentProductId!=dto.InvestmentProductId);if(dto.IsActive&&await Overlaps(dto.InvestmentProductId,dto.MinimumAmount,dto.MaximumAmount,dto.MinimumTermDays,dto.MaximumTermDays,dto.EffectiveFrom,dto.EffectiveTo,id))throw new InvestmentRateOverlapException();x.InvestmentProductId=dto.InvestmentProductId;x.MinimumAmount=dto.MinimumAmount;x.MaximumAmount=dto.MaximumAmount;x.MinimumTermDays=dto.MinimumTermDays;x.MaximumTermDays=dto.MaximumTermDays;x.AnnualInterestRate=dto.AnnualInterestRate;x.EffectiveFrom=dto.EffectiveFrom;x.EffectiveTo=dto.EffectiveTo;x.IsActive=dto.IsActive;x.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync();return true;}
 public async Task<bool> DeleteAsync(Guid id){var x=await db.InvestmentRates.FindAsync(id);if(x is null)return false;x.IsActive=false;x.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync();return true;}
 private async Task EnsureProduct(Guid id,bool active){var p=await db.InvestmentProducts.FindAsync(id);if(p is null)throw new InvestmentProductNotFoundException();if(active&&!p.IsActive)throw new ArgumentException("An inactive investment product cannot receive a rate.");}
 private Task<bool> Overlaps(Guid p,decimal? min,decimal? max,int? days,int? maxDays,DateTimeOffset from,DateTimeOffset? to,Guid? exclude){var end=max??decimal.MaxValue;var start=min??decimal.MinValue;var dayEnd=maxDays??int.MaxValue;var dayStart=days??int.MinValue;var dateEnd=to??DateTimeOffset.MaxValue;return db.InvestmentRates.AnyAsync(x=>x.InvestmentProductId==p&&x.IsActive&&x.Id!=exclude&&(x.MinimumAmount==null||x.MinimumAmount<=end)&&(x.MaximumAmount==null||x.MaximumAmount>=start)&&(x.MinimumTermDays==null||x.MinimumTermDays<=dayEnd)&&(x.MaximumTermDays==null||x.MaximumTermDays>=dayStart)&&x.EffectiveFrom<=dateEnd&&(x.EffectiveTo==null||x.EffectiveTo>=from));}
 private static void Validate(decimal? min,decimal? max,int? days,int? maxDays,decimal rate,DateTimeOffset from,DateTimeOffset? to){if((min.HasValue&&min<=0)||(max.HasValue&&max<=0)||(min.HasValue&&max.HasValue&&max<min)||(days.HasValue&&days<=0)||(maxDays.HasValue&&maxDays<=0)||(days.HasValue&&maxDays.HasValue&&maxDays<days)||rate<=0||from==default||to<from)throw new ArgumentException("Invalid investment rate configuration.");}
 private static InvestmentRateDto Map(InvestmentRate x)=>new(){Id=x.Id,InvestmentProductId=x.InvestmentProductId,InvestmentProductName=x.InvestmentProduct.Name,MinimumAmount=x.MinimumAmount,MaximumAmount=x.MaximumAmount,MinimumTermDays=x.MinimumTermDays,MaximumTermDays=x.MaximumTermDays,AnnualInterestRate=x.AnnualInterestRate,EffectiveFrom=x.EffectiveFrom,EffectiveTo=x.EffectiveTo,IsActive=x.IsActive,CreatedAt=x.CreatedAt,UpdatedAt=x.UpdatedAt};
}
