import { CurrencyPipe, DatePipe } from '@angular/common';
import { Component, DestroyRef, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { RouterLink } from '@angular/router';
import { AuthStateService } from '../../../core/auth/services/auth-state.service';
import { InvestmentApplication, InvestmentApplicationStatus } from '../../investments/application/models/investment-application.model';
import { InvestmentApplicationService } from '../../investments/application/services/investment-application.service';

@Component({
  selector: 'app-client-dashboard', imports: [RouterLink, DatePipe, CurrencyPipe],
  template: `<main class="client-page"><header class="welcome"><p>Tu espacio financiero</p><h1>Hola, {{ authState.currentUser()?.firstName || 'cliente' }}</h1><span>¿Qué deseas hacer hoy?</span></header><section class="quick-grid"><a class="quick-card" routerLink="/client/credits/simulator"><i>₵</i><div><h2>Simular crédito</h2><p>Calcula cuotas y condiciones a tu medida.</p><span>Comenzar <b>→</b></span></div></a><a class="quick-card" routerLink="/client/credits/comparison"><i>≋</i><div><h2>Comparar sistemas</h2><p>Conoce las diferencias entre ambas opciones.</p><span>Comparar <b>→</b></span></div></a><a class="quick-card" routerLink="/client/investments/simulator"><i>↗</i><div><h2>Simular inversión</h2><p>Proyecta el rendimiento de tu dinero.</p><span>Simular <b>→</b></span></div></a></section><section id="my-applications" class="applications"><div class="section-heading"><div><p>Seguimiento</p><h2>Mis solicitudes recientes</h2></div></div>@if (loading()) { <p class="muted">Cargando solicitudes…</p> } @else if (error()) { <p class="error">No fue posible cargar tus solicitudes.</p> } @else if (applications().length === 0) { <div class="no-applications"><span>▤</span><strong>Aún no tienes solicitudes de inversión.</strong><p>Cuando decidas invertir, aquí podrás consultar su avance.</p></div> } @else { <div class="table-container"><table class="data-table"><thead><tr><th>Número</th><th>Producto</th><th>Monto</th><th>Estado</th><th>Fecha</th><th></th></tr></thead><tbody>@for (application of applications(); track application.id) { <tr><td>{{ application.applicationNumber }}</td><td>{{ application.investmentProductName }}</td><td>{{ application.amount | currency:'USD':'symbol':'1.2-2' }}</td><td><span class="status">{{ statusLabel(application.status) }}</span></td><td>{{ application.createdAt | date:'dd/MM/yyyy':'UTC' }}</td><td><a class="view" [routerLink]="['/client/investments/applications', application.id]">Ver</a></td></tr> }</tbody></table></div> }</section></main>`,
  styles: [`.client-page{width:min(100%,1260px);margin:auto;padding:48px 30px}.welcome p,.section-heading p{margin:0;color:var(--accent);font-size:.78rem;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.welcome h1{margin:8px 0;font-size:clamp(2rem,4vw,3rem);letter-spacing:-.04em}.welcome>span{color:var(--text-muted)}.quick-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin:32px 0}.quick-card{display:flex;gap:15px;padding:22px;border:1px solid var(--border);border-radius:var(--radius-md);background:var(--surface);box-shadow:var(--shadow-sm);transition:.18s}.quick-card:hover{transform:translateY(-3px);border-color:#b7d9d5;box-shadow:var(--shadow-md)}.quick-card i{display:grid;width:42px;height:42px;place-items:center;border-radius:12px;background:var(--primary-soft);color:var(--primary);font-size:1.25rem;font-style:normal;font-weight:800}.quick-card div{display:grid;gap:7px}.quick-card h2,.quick-card p{margin:0}.quick-card h2{font-size:1rem}.quick-card p{color:var(--text-muted);font-size:.87rem;line-height:1.45}.quick-card span{margin-top:4px;color:var(--primary);font-size:.85rem;font-weight:800}.quick-card b{margin-left:5px}.applications{padding:24px;border:1px solid var(--border);border-radius:var(--radius-md);background:var(--surface);box-shadow:var(--shadow-sm)}.section-heading{margin-bottom:18px}.section-heading h2{margin:6px 0 0;font-size:1.2rem}.error{color:var(--danger)}.status{padding:5px 9px;border-radius:999px;background:#effaf4;color:var(--success);font-size:.75rem;font-weight:700}.view{color:var(--primary);font-size:.83rem;font-weight:800}.no-applications{display:grid;justify-items:center;gap:7px;padding:32px 12px;text-align:center}.no-applications span{display:grid;width:42px;height:42px;place-items:center;border-radius:12px;background:var(--primary-soft);color:var(--primary)}.no-applications p{margin:0;color:var(--text-muted)}@media(max-width:850px){.quick-grid{grid-template-columns:1fr}.client-page{padding:30px 16px}}`]
})
export class ClientDashboardComponent {
  private readonly service = inject(InvestmentApplicationService); private readonly destroyRef = inject(DestroyRef); readonly authState = inject(AuthStateService); readonly applications = signal<InvestmentApplication[]>([]); readonly loading = signal(true); readonly error = signal(false);
  constructor() { this.service.getMine().pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: applications => { this.applications.set(applications.slice(0,5)); this.loading.set(false); }, error: () => { this.error.set(true); this.loading.set(false); } }); }
  statusLabel(status: InvestmentApplicationStatus): string { return ({ Draft:'Borrador', PendingDocuments:'Pendiente de documentos', PendingIdentityVerification:'Pendiente de identidad', ReadyForReview:'Lista para enviar', Submitted:'En revisión', Approved:'Aprobada', Rejected:'Rechazada', Cancelled:'Cancelada' } as Record<InvestmentApplicationStatus,string>)[status]; }
}
