using FinanSmart.Api.Common.Enums; using FinanSmart.Api.Common.Exceptions; using FinanSmart.Api.Data.Context; using FinanSmart.Api.Entities; using FinanSmart.Api.Modules.Investments.IdentityVerification.DTOs; using FinanSmart.Api.Modules.Investments.IdentityVerification.Interfaces; using Microsoft.AspNetCore.Hosting; using Microsoft.AspNetCore.Http; using Microsoft.EntityFrameworkCore;
namespace FinanSmart.Api.Modules.Investments.IdentityVerification.Services;
public class InvestmentIdentityVerificationService(FinanSmartDbContext db,IWebHostEnvironment environment):IInvestmentIdentityVerificationService
{
 const long MaxSize=5*1024*1024; static readonly IReadOnlyDictionary<string,string> Allowed=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase){[".jpg"]="image/jpeg",[".jpeg"]="image/jpeg",[".png"]="image/png"};
 public async Task<InvestmentIdentityVerificationDto?> GetAsync(Guid id){var v=await db.InvestmentIdentityVerifications.AsNoTracking().FirstOrDefaultAsync(x=>x.InvestmentApplicationId==id);return v is null?null:Map(v);}
 public async Task<InvestmentIdentityVerificationDto> UploadSelfieAsync(Guid id,IFormFile file){var app=await Application(id);Editable(app); Validate(file); var verification=await db.InvestmentIdentityVerifications.FirstOrDefaultAsync(x=>x.InvestmentApplicationId==id); if(verification?.Status==IdentityVerificationStatus.Verified)throw new IdentityVerificationException("The identity verification is already complete."); var extension=Path.GetExtension(file.FileName).ToLowerInvariant();var filename=$"{Guid.NewGuid():N}{extension}";var directory=Path.Combine(environment.ContentRootPath,"Storage","InvestmentIdentityVerification",id.ToString());Directory.CreateDirectory(directory);await using(var stream=File.Create(Path.Combine(directory,filename)))await file.CopyToAsync(stream);var now=DateTimeOffset.UtcNow;if(verification is null){verification=new InvestmentIdentityVerification{Id=Guid.NewGuid(),InvestmentApplicationId=id,CreatedAt=now};db.InvestmentIdentityVerifications.Add(verification);}verification.SelfieOriginalFileName=Path.GetFileName(file.FileName);verification.SelfieStoredFileName=filename;verification.SelfieStoragePath=Path.Combine(id.ToString(),filename);verification.SelfieContentType=Allowed[extension];verification.SelfieFileSize=file.Length;verification.Status=IdentityVerificationStatus.Captured;verification.ConsentAccepted=false;verification.CapturedAt=now;verification.VerifiedAt=null;verification.UpdatedAt=now;await db.SaveChangesAsync();return Map(verification);}
 public async Task<IdentitySelfieDownload?> GetSelfieAsync(Guid id){var v=await db.InvestmentIdentityVerifications.AsNoTracking().FirstOrDefaultAsync(x=>x.InvestmentApplicationId==id&&x.Status!=IdentityVerificationStatus.Pending);if(v?.SelfieStoragePath is null||v.SelfieContentType is null)return null;var root=Path.GetFullPath(Path.Combine(environment.ContentRootPath,"Storage","InvestmentIdentityVerification"));var path=Path.GetFullPath(Path.Combine(root,v.SelfieStoragePath));return !path.StartsWith(root,StringComparison.OrdinalIgnoreCase)||!File.Exists(path)?null:new(File.OpenRead(path),v.SelfieContentType);}
 public async Task<InvestmentIdentityVerificationDto> VerifyAsync(Guid id,bool consent){var app=await Application(id);Editable(app);var v=await db.InvestmentIdentityVerifications.FirstOrDefaultAsync(x=>x.InvestmentApplicationId==id)??throw new IdentityVerificationException("First register a photograph.");if(v.Status!=IdentityVerificationStatus.Captured)throw new IdentityVerificationException("First register a photograph.");if(!consent)throw new IdentityVerificationException("Consent is required to continue.");var now=DateTimeOffset.UtcNow;v.Status=IdentityVerificationStatus.Verified;v.ConsentAccepted=true;v.VerifiedAt=now;v.UpdatedAt=now;app.CurrentStep=InvestmentApplicationStep.Declarations;app.Status=InvestmentApplicationStatus.PendingIdentityVerification;app.UpdatedAt=now;await db.SaveChangesAsync();return Map(v);}
 async Task<InvestmentApplication> Application(Guid id)=>await db.InvestmentApplications.FindAsync(id)??throw new IdentityVerificationException("Investment application was not found.",404);
 static void Editable(InvestmentApplication app){if(app.Status==InvestmentApplicationStatus.Cancelled)throw new IdentityVerificationException("A cancelled application is read-only.");if(app.Status!=InvestmentApplicationStatus.PendingIdentityVerification||app.CurrentStep!=InvestmentApplicationStep.IdentityVerification)throw new IdentityVerificationException("Identity verification is not available in the current step.");}
 static void Validate(IFormFile file){if(file is null||file.Length==0)throw new IdentityVerificationException("A photograph is required.");if(file.Length>MaxSize)throw new IdentityVerificationException("The image exceeds the maximum size.",413);var ext=Path.GetExtension(file.FileName).ToLowerInvariant();if(!Allowed.TryGetValue(ext,out var type)||!string.Equals(type,file.ContentType,StringComparison.OrdinalIgnoreCase))throw new IdentityVerificationException("Only JPG or PNG images are allowed.",415);}
 static InvestmentIdentityVerificationDto Map(InvestmentIdentityVerification v)=>new(){Id=v.Id,InvestmentApplicationId=v.InvestmentApplicationId,Status=v.Status,ConsentAccepted=v.ConsentAccepted,SelfieContentType=v.SelfieContentType,SelfieFileSize=v.SelfieFileSize,CapturedAt=v.CapturedAt,VerifiedAt=v.VerifiedAt};
}
