import { Component, DestroyRef, inject, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { Router } from '@angular/router';
import { NonNullableFormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { PageHeaderComponent } from '../../../shared/components/page-header/page-header.component';
import { LoadingSpinnerComponent } from '../../../shared/components/loading-spinner/loading-spinner.component';
import { CreditType } from '../../admin/credits/credit-types/models/credit-type.model';
import { CreditTypeService } from '../../admin/credits/credit-types/services/credit-type.service';
import { CreditRateService } from '../../admin/credits/credit-rates/services/credit-rate.service';
import { AmortizationInstallment, AmortizationSystem, CreditSimulationRequest, CreditSimulationResponse } from './models/credit-simulation.model';
import { CreditSimulationService } from './services/credit-simulation.service';

@Component({selector:'app-credit-simulator',imports:[ReactiveFormsModule,DatePipe,PageHeaderComponent,LoadingSpinnerComponent],templateUrl:'./credit-simulator.component.html',styleUrl:'./credit-simulator.component.scss'})
export class CreditSimulatorComponent {
  private readonly destroy=inject(DestroyRef); private readonly fb=inject(NonNullableFormBuilder); private readonly typeApi=inject(CreditTypeService); private readonly rateApi=inject(CreditRateService); private readonly api=inject(CreditSimulationService); private readonly router=inject(Router); private readonly currency=new Intl.NumberFormat('es-EC',{style:'currency',currency:'USD'}); private readonly percentFormat=new Intl.NumberFormat('es-EC',{minimumFractionDigits:2,maximumFractionDigits:2});
  readonly creditTypes=signal<CreditType[]>([]); readonly selectedType=signal<CreditType|null>(null); readonly currentRate=signal<number|null>(null); readonly rateChecked=signal(false); readonly loadingTypes=signal(true); readonly simulating=signal(false); readonly downloadingPdf=signal(false); readonly result=signal<CreditSimulationResponse|null>(null); readonly resultStale=signal(false); readonly showTable=signal(false); readonly showBreakdown=signal(false); readonly error=signal(''); readonly expandedInstallment=signal<number|null>(null);
  readonly minimumStartDate=new Date().toISOString().slice(0,10);
  isPublic():boolean{return this.router.url.startsWith('/simulators/') || this.router.url.startsWith('/client/');}
  readonly form=this.fb.group({creditTypeId:['',Validators.required],amount:[0,Validators.required],termMonths:[0,Validators.required],amortizationSystem:['French' as AmortizationSystem,Validators.required],startDate:[this.minimumStartDate,Validators.required]});
  constructor(){this.typeApi.getAll().pipe(takeUntilDestroyed(this.destroy)).subscribe({next:types=>{this.creditTypes.set(types.filter(x=>x.isActive));this.loadingTypes.set(false);this.configureType(this.form.controls.creditTypeId.value);},error:()=>{this.error.set('No se pudo conectar con el servidor.');this.loadingTypes.set(false);}});this.form.controls.creditTypeId.valueChanges.pipe(takeUntilDestroyed(this.destroy)).subscribe(id=>this.configureType(id));this.form.valueChanges.pipe(takeUntilDestroyed(this.destroy)).subscribe(()=>{if(this.result())this.resultStale.set(true);});}
  private configureType(id:string){const type=this.creditTypes().find(x=>x.id===id)??null;this.selectedType.set(type);this.currentRate.set(null);this.rateChecked.set(false);const amountValidators=type?[Validators.required,Validators.min(.01)]:[Validators.required,Validators.min(.01)];const termValidators=type?[Validators.required,Validators.min(1)]:[Validators.required,Validators.min(1)];if(type&&type.minimumAmount!==null)amountValidators.push(Validators.min(type.minimumAmount));if(type&&type.maximumAmount!==null)amountValidators.push(Validators.max(type.maximumAmount));if(type&&type.minimumTermMonths!==null)termValidators.push(Validators.min(type.minimumTermMonths));if(type&&type.maximumTermMonths!==null)termValidators.push(Validators.max(type.maximumTermMonths));this.form.controls.amount.setValidators(amountValidators);this.form.controls.termMonths.setValidators(termValidators);this.form.controls.amount.updateValueAndValidity({emitEvent:false});this.form.controls.termMonths.updateValueAndValidity({emitEvent:false});if(type)this.rateApi.getCurrentRate(type.id).pipe(takeUntilDestroyed(this.destroy)).subscribe({next:rate=>{this.currentRate.set(Number(rate.annualInterestRate));this.rateChecked.set(true);},error:()=>this.rateChecked.set(true)});}
  isValid():boolean{const t=this.selectedType(),v=this.form.getRawValue();return !!t&&this.form.valid&&this.isStartDateValid()&&this.rateChecked()&&this.currentRate()!==null&&(t.minimumAmount===null||v.amount>=t.minimumAmount)&&(t.maximumAmount===null||v.amount<=t.maximumAmount)&&Number.isInteger(v.termMonths)&&(t.minimumTermMonths===null||v.termMonths>=t.minimumTermMonths)&&(t.maximumTermMonths===null||v.termMonths<=t.maximumTermMonths);}
  isStartDateValid():boolean{return this.form.controls.startDate.value>=this.minimumStartDate;}
  amountError(){const t=this.selectedType(),v=this.form.controls.amount.value;if(!t||v<=0)return 'Selecciona un tipo e ingresa un monto positivo.';if(t.minimumAmount!==null&&v<t.minimumAmount)return `El monto mínimo para ${t.name} es ${this.money(t.minimumAmount)}.`;return t.maximumAmount!==null&&v>t.maximumAmount?`El monto máximo para ${t.name} es ${this.money(t.maximumAmount)}.`:'';}
  termError(){const t=this.selectedType(),v=this.form.controls.termMonths.value;if(!t||!Number.isInteger(v)||v<=0)return 'Selecciona un tipo e ingresa un plazo entero positivo.';if(t.minimumTermMonths!==null&&v<t.minimumTermMonths)return `El plazo mínimo para ${t.name} es ${t.minimumTermMonths} meses.`;return t.maximumTermMonths!==null&&v>t.maximumTermMonths?`El plazo máximo para ${t.name} es ${t.maximumTermMonths} meses.`:'';}
  limitSummary(type:CreditType):string{const amount=type.minimumAmount!==null&&type.maximumAmount!==null?`${this.money(type.minimumAmount)} – ${this.money(type.maximumAmount)}`:type.minimumAmount!==null?`Desde ${this.money(type.minimumAmount)}`:type.maximumAmount!==null?`Hasta ${this.money(type.maximumAmount)}`:'Monto no especificado';const term=type.minimumTermMonths!==null&&type.maximumTermMonths!==null?`${type.minimumTermMonths}–${type.maximumTermMonths} meses`:type.minimumTermMonths!==null?`Desde ${type.minimumTermMonths} meses`:type.maximumTermMonths!==null?`Hasta ${type.maximumTermMonths} meses`:'Plazo no especificado';return `${amount} · ${term}`;}
  selectSystem(s:AmortizationSystem){this.form.controls.amortizationSystem.setValue(s);} money(x:number){return this.currency.format(x);} percent(x:number){return this.percentFormat.format(x)+' %';} systemLabel(s:AmortizationSystem){return s==='French'?'Sistema Francés':'Sistema Alemán';} systemDescription(s:AmortizationSystem){return s==='French'?'La cuota financiera se mantiene prácticamente constante.':'El abono a capital es constante y las cuotas disminuyen progresivamente.';} toggleCharges(i:AmortizationInstallment){this.expandedInstallment.update(x=>x===i.installmentNumber?null:i.installmentNumber);}
  chargeLabel(name:string):string{return name.trim().toLowerCase()==='installment protection'?'Protección de cuotas':name;}
  chargeTotals(simulation:CreditSimulationResponse): [string, number][] {
    const totals = simulation.installments.flatMap(item => item.charges).reduce((result, charge) => {
      result[charge.name] = (result[charge.name] ?? 0) + charge.calculatedAmount;
      return result;
    }, {} as Record<string, number>);
    return Object.entries(totals);
  }
  viewTable(){this.showTable.set(true);setTimeout(()=>document.getElementById('amortization-table')?.scrollIntoView({behavior:'smooth',block:'start'}));}
  simulate(){if(!this.isValid()||this.simulating()){this.form.markAllAsTouched();return;}this.simulating.set(true);this.error.set('');const v=this.form.getRawValue();this.api.simulate({...v,startDate:v.startDate+'T00:00:00Z'} as CreditSimulationRequest).pipe(takeUntilDestroyed(this.destroy)).subscribe({next:r=>{this.result.set(r);this.resultStale.set(false);this.showTable.set(false);this.showBreakdown.set(false);this.simulating.set(false);},error:e=>{this.error.set(this.errorMessage(e));this.simulating.set(false);}});}
  downloadPdf(){if(!this.result()||this.resultStale())return;this.downloadingPdf.set(true);const v=this.form.getRawValue();this.api.downloadPdf({...v,startDate:v.startDate+'T00:00:00Z'} as CreditSimulationRequest).pipe(takeUntilDestroyed(this.destroy)).subscribe({next:b=>{const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='simulacion-credito.pdf';a.click();URL.revokeObjectURL(u);this.downloadingPdf.set(false);},error:()=>{this.error.set('No fue posible generar el PDF.');this.downloadingPdf.set(false);}});}
  newSimulation(){this.result.set(null);this.resultStale.set(false);} private errorMessage(e:HttpErrorResponse){return e.status===404?'No existe una tasa vigente para el tipo de crédito seleccionado.':'No fue posible procesar la simulación.';}
}
