using FinanSmart.Api.Common.Enums; using FinanSmart.Api.Common.Exceptions; using FinanSmart.Api.Data.Context; using FinanSmart.Api.Entities; using FinanSmart.Api.Modules.Investments.Products.DTOs; using FinanSmart.Api.Modules.Investments.Products.Interfaces; using Microsoft.EntityFrameworkCore;
namespace FinanSmart.Api.Modules.Investments.Products.Services;
public class InvestmentProductService(FinanSmartDbContext db) : IInvestmentProductService
{
 public async Task<IReadOnlyCollection<InvestmentProductDto>> GetAllAsync()=>await db.InvestmentProducts.AsNoTracking().OrderBy(x=>x.Name).Select(x=>Map(x)).ToListAsync();
 public async Task<InvestmentProductDto?> GetByIdAsync(Guid id){var x=await db.InvestmentProducts.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==id);return x is null?null:Map(x);}
 public async Task<InvestmentProductDto> CreateAsync(CreateInvestmentProductDto dto){ Validate(dto.Name,dto.MinimumAmount,dto.MaximumAmount,dto.MinimumTermDays,dto.MaximumTermDays,dto.InterestCalculationMethod,dto.InterestPaymentFrequency); await EnsureName(dto.Name,null,dto.IsActive); var now=DateTimeOffset.UtcNow; var x=new InvestmentProduct{Id=Guid.NewGuid(),Name=dto.Name.Trim(),Description=dto.Description,MinimumAmount=dto.MinimumAmount,MaximumAmount=dto.MaximumAmount,MinimumTermDays=dto.MinimumTermDays,MaximumTermDays=dto.MaximumTermDays,InterestCalculationMethod=dto.InterestCalculationMethod,InterestPaymentFrequency=dto.InterestPaymentFrequency,IsActive=dto.IsActive,CreatedAt=now,UpdatedAt=now};db.InvestmentProducts.Add(x);await db.SaveChangesAsync();return Map(x);}
 public async Task<bool> UpdateAsync(Guid id,UpdateInvestmentProductDto dto){Validate(dto.Name,dto.MinimumAmount,dto.MaximumAmount,dto.MinimumTermDays,dto.MaximumTermDays,dto.InterestCalculationMethod,dto.InterestPaymentFrequency);var x=await db.InvestmentProducts.FindAsync(id);if(x is null)return false;await EnsureName(dto.Name,id,dto.IsActive);x.Name=dto.Name.Trim();x.Description=dto.Description;x.MinimumAmount=dto.MinimumAmount;x.MaximumAmount=dto.MaximumAmount;x.MinimumTermDays=dto.MinimumTermDays;x.MaximumTermDays=dto.MaximumTermDays;x.InterestCalculationMethod=dto.InterestCalculationMethod;x.InterestPaymentFrequency=dto.InterestPaymentFrequency;x.IsActive=dto.IsActive;x.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync();return true;}
 public async Task<bool> DeleteAsync(Guid id){var x=await db.InvestmentProducts.FindAsync(id);if(x is null)return false;x.IsActive=false;x.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync();return true;}
 private async Task EnsureName(string name,Guid? id,bool active){if(active&&await db.InvestmentProducts.AnyAsync(x=>x.IsActive&&x.Id!=id&&x.Name.ToLower()==name.Trim().ToLower()))throw new InvestmentProductNameConflictException();}
 private static void Validate(string name,decimal? min,decimal? max,int? minDays,int? maxDays,InterestCalculationMethod method,InterestPaymentFrequency frequency){if(string.IsNullOrWhiteSpace(name)||(min.HasValue&&min<=0)||(max.HasValue&&max<=0)||(min.HasValue&&max.HasValue&&max<min)||(minDays.HasValue&&minDays<=0)||(maxDays.HasValue&&maxDays<=0)||(minDays.HasValue&&maxDays.HasValue&&maxDays<minDays)||!Enum.IsDefined(method)||!Enum.IsDefined(frequency))throw new ArgumentException("Invalid investment product configuration.");}
 private static InvestmentProductDto Map(InvestmentProduct x)=>new(){Id=x.Id,Name=x.Name,Description=x.Description,MinimumAmount=x.MinimumAmount,MaximumAmount=x.MaximumAmount,MinimumTermDays=x.MinimumTermDays,MaximumTermDays=x.MaximumTermDays,InterestCalculationMethod=x.InterestCalculationMethod,InterestPaymentFrequency=x.InterestPaymentFrequency,IsActive=x.IsActive,CreatedAt=x.CreatedAt,UpdatedAt=x.UpdatedAt};
}
