import { Component, ElementRef, HostListener, inject, signal } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { AuthStateService } from '../../core/auth/services/auth-state.service';
import { InstitutionStateService } from '../../core/services/institution-state.service';

@Component({
  selector: 'app-client-layout', standalone: true, imports: [RouterLink, RouterLinkActive, RouterOutlet],
  template: `<div class="client-shell"><header><a class="client-brand" routerLink="/client/dashboard"><span>@if(institution.currentInstitution()?.logoUrl && !logoFailed()){<img [src]="institution.currentInstitution()?.logoUrl" alt="Logo institucional" (error)="logoFailed.set(true)">}@else{ {{ brandInitials() }} }</span><strong>{{ institution.currentInstitution()?.name || 'FinanSmart' }}</strong></a><nav><a routerLink="/client/dashboard" routerLinkActive="active">Inicio</a><a routerLink="/client/credits/simulator" routerLinkActive="active">Crédito</a><a routerLink="/client/credits/comparison" routerLinkActive="active">Comparar</a><a routerLink="/client/investments/simulator" routerLinkActive="active">Inversión</a></nav><div class="user-menu"><button class="user-button" (click)="open.set(!open())"><span class="avatar">{{ initials() }}</span><span class="user-copy"><strong>{{ fullName() }}</strong><small>Cliente</small></span><span class="chevron">⌄</span></button>@if(open()){<div class="dropdown"><p>{{ auth.currentUser()?.email }}</p><hr><button (click)="logout()">Cerrar sesión</button></div>}</div></header><router-outlet/></div>`,
  styles: [`.client-shell{min-height:100dvh}.client-shell header{display:flex;align-items:center;min-height:72px;gap:28px;padding:0 max(24px,calc((100% - 1260px)/2));border-bottom:1px solid var(--border);background:rgb(255 255 255 / 94%);backdrop-filter:blur(10px)}.client-brand{display:flex;align-items:center;gap:8px;color:var(--primary);font-weight:800}.client-brand span,.avatar{display:grid;place-items:center;background:var(--primary);color:#fff;font-weight:800}.client-brand span{width:31px;height:31px;overflow:hidden;border-radius:9px}.client-brand img{width:100%;height:100%;object-fit:contain;background:#fff}.client-shell nav{display:flex;gap:22px;flex:1}.client-shell nav a{position:relative;padding:25px 0;color:var(--text-muted);font-size:.87rem}.client-shell nav a.active{color:var(--primary);font-weight:800}.client-shell nav a.active:after{position:absolute;right:0;bottom:0;left:0;height:3px;background:var(--accent);content:''}.user-menu{position:relative}.user-button{display:flex;align-items:center;gap:9px;border:0;border-radius:12px;background:transparent;padding:5px 7px;color:var(--text);text-align:left;cursor:pointer}.avatar{width:38px;height:38px;border-radius:50%}.user-copy{display:grid;gap:2px;font-size:.84rem}.user-copy small,.dropdown p{color:var(--text-muted);font-size:.72rem}.chevron{color:var(--text-muted)}.dropdown{position:absolute;right:0;top:calc(100% + 10px);z-index:20;width:235px;padding:10px;border:1px solid var(--border);border-radius:12px;background:var(--surface);box-shadow:var(--shadow-md)}.dropdown p{margin:3px 5px 10px;overflow-wrap:anywhere}.dropdown hr{border:0;border-top:1px solid var(--border)}.dropdown button{width:100%;border:0;border-radius:8px;background:transparent;padding:10px;text-align:left;color:var(--danger);font-weight:700;cursor:pointer}`]
})
export class ClientLayoutComponent {
  private readonly host = inject(ElementRef); readonly auth = inject(AuthStateService); readonly institution = inject(InstitutionStateService); readonly open = signal(false); readonly logoFailed = signal(false);
  @HostListener('document:click', ['$event']) closeOnOutsideClick(event: Event): void { if (!this.host.nativeElement.contains(event.target)) this.open.set(false); }
  fullName(): string { const user = this.auth.currentUser(); return user ? `${user.firstName} ${user.lastName}`.trim() : 'Cliente'; }
  initials(): string { return this.fullName().split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase(); }
  brandInitials(): string { return (this.institution.currentInstitution()?.name || 'FinanSmart').split(' ').filter(Boolean).slice(0, 2).map(part => part[0]).join('').toUpperCase(); }
  logout(): void { this.open.set(false); this.auth.logout().subscribe(); }
}
