import { Component, inject } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { AuthStateService } from '../../core/auth/services/auth-state.service';

@Component({
  selector: 'app-client-layout', imports: [RouterLink, RouterLinkActive, RouterOutlet],
  template: `<div class="client-shell"><header><a class="client-brand" routerLink="/client/dashboard"><span>F</span><strong>FinanSmart</strong></a><nav aria-label="Navegación de cliente"><a routerLink="/client/dashboard" routerLinkActive="active">Inicio</a><a routerLink="/client/credits/simulator" routerLinkActive="active">Crédito</a><a routerLink="/client/credits/comparison" routerLinkActive="active">Comparar</a><a routerLink="/client/investments/simulator" routerLinkActive="active">Inversión</a></nav><div class="client-user"><span class="client-avatar">{{ initials() }}</span><span class="client-user-name"><strong>{{ fullName() }}</strong><small>Cliente</small></span><button class="logout-button" type="button" (click)="logout()">Cerrar sesión</button></div></header><router-outlet /></div>`,
  styles: [`.client-shell{min-height:100dvh}.client-shell header{display:flex;align-items:center;min-height:72px;gap:28px;padding:0 max(24px,calc((100% - 1260px)/2));border-bottom:1px solid var(--border);background:rgb(255 255 255 / 94%);backdrop-filter:blur(10px)}.client-brand{display:flex;align-items:center;gap:8px;color:var(--primary);font-weight:800}.client-brand span{display:grid;width:31px;height:31px;place-items:center;border-radius:9px;background:var(--primary);color:#fff;font-size:.8rem}.client-shell nav{display:flex;gap:22px;flex:1}.client-shell nav a{position:relative;padding:25px 0;color:var(--text-muted);font-size:.87rem}.client-shell nav a.active{color:var(--primary);font-weight:800}.client-shell nav a.active:after{position:absolute;right:0;bottom:0;left:0;height:3px;border-radius:99px;background:var(--accent);content:''}.client-user{display:flex;align-items:center;gap:9px}.client-avatar{display:grid;width:36px;height:36px;place-items:center;border-radius:50%;background:var(--primary-soft);color:var(--primary);font-size:.78rem;font-weight:800}.client-user-name{display:grid;gap:2px;font-size:.82rem}.client-user-name small{color:var(--text-muted);font-size:.7rem}.logout-button{border:0;background:transparent;color:var(--primary);font-size:.8rem;font-weight:800;white-space:nowrap}@media(max-width:767px){.client-shell header{gap:12px;padding:0 16px;overflow-x:auto}.client-shell nav{gap:15px;white-space:nowrap}.client-shell nav a{padding:22px 0}.client-user-name,.logout-button{display:none}.client-brand strong{font-size:.83rem}}`]
})
export class ClientLayoutComponent { readonly authState=inject(AuthStateService); fullName():string{const user=this.authState.currentUser();return user?`${user.firstName} ${user.lastName}`.trim():'Cliente';} initials():string{return this.fullName().split(' ').filter(Boolean).map(name=>name[0]).join('').slice(0,2).toUpperCase()||'C';} logout():void{this.authState.logout().subscribe();} }
