import { Component, input, output, signal } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { Institution } from '../../features/admin/institution/models/institution.model';

@Component({
  selector: 'app-admin-sidebar', imports: [RouterLink, RouterLinkActive],
  template: `<aside class="sidebar" [class.collapsed]="collapsed()" [class.mobile-open]="mobileOpen()"><div class="brand"><span class="brand-mark">{{ initials() }}</span><span class="brand-copy"><strong>{{ institution()?.name || 'FinanSmart' }}</strong><small>Panel administrativo</small></span><button class="mobile-close" type="button" aria-label="Cerrar menú" (click)="navigated.emit()">×</button></div><nav aria-label="Navegación administrativa">@for (section of menu; track section.label) {<p class="nav-section">{{ section.label }}</p>@for (item of section.items; track item.path) {<a [routerLink]="item.path" routerLinkActive="active" (click)="navigated.emit()"><svg class="nav-icon" viewBox="0 0 24 24" aria-hidden="true"><path [attr.d]="item.icon" /></svg><span>{{ item.label }}</span></a>}}</nav></aside>`,
  styles: [`.sidebar{position:sticky;top:0;width:250px;height:100dvh;flex:0 0 auto;overflow-y:auto;background:linear-gradient(180deg,#092b46,#0c3a5b);color:#dcecf4;padding:18px 12px;transition:width .22s ease;z-index:30;scrollbar-width:thin}.brand{display:flex;align-items:center;gap:11px;min-height:60px;padding:5px 8px 22px;border-bottom:1px solid rgb(255 255 255 / 12%)}.brand-mark{display:grid;place-items:center;width:40px;height:40px;border-radius:13px;background:linear-gradient(135deg,#20b4a4,#128a80);color:#fff;font-weight:800;box-shadow:0 7px 18px rgb(0 0 0 / 18%)}.brand-copy{display:grid;gap:3px;min-width:0}.brand-copy strong{overflow:hidden;color:#fff;font-size:.9rem;text-overflow:ellipsis;white-space:nowrap}.brand-copy small{color:#a8c2d0;font-size:.7rem}.mobile-close{display:none;margin-left:auto;border:0;background:transparent;color:#fff;font-size:1.65rem}.sidebar nav{display:grid;gap:3px;padding:8px 0 18px}.nav-section{margin:20px 10px 7px;color:#83a5b7;font-size:.67rem;font-weight:800;letter-spacing:.1em}.sidebar a{position:relative;display:flex;align-items:center;gap:12px;min-height:44px;padding:0 11px;border-radius:10px;color:#d9e8ef;font-size:.9rem;transition:background .16s,color .16s}.nav-icon{width:19px;height:19px;flex:0 0 auto;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.sidebar a:hover{background:rgb(255 255 255 / 8%);color:#fff}.sidebar a.active{background:rgb(255 255 255 / 13%);color:#fff;font-weight:700}.sidebar a.active:before{position:absolute;left:-12px;width:4px;height:24px;border-radius:0 4px 4px 0;background:#20b4a4;content:''}.collapsed{width:76px}.collapsed .brand-copy,.collapsed .nav-section,.collapsed a span:last-child{display:none}.collapsed .brand{justify-content:center}.collapsed a{justify-content:center}.collapsed a.active:before{left:-12px}@media(max-width:767px){.sidebar{position:fixed;left:0;transform:translateX(-105%);width:270px;box-shadow:var(--shadow-md);transition:transform .22s ease}.sidebar.mobile-open{transform:translateX(0)}.mobile-close{display:block}}`]
})
export class AdminSidebarComponent {
  readonly collapsed = input(false); readonly mobileOpen = input(false); readonly institution = input<Institution | null>(null); readonly navigated = output<void>(); readonly logoFailed = signal(false);
  readonly menu = [
    { label: 'GENERAL', items: [{ label: 'Dashboard', path: '/admin/dashboard', icon: 'M3 12l9-8 9 8v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z M9 22v-6h6v6' }] },
    { label: 'CRÉDITOS', items: [{ label: 'Tipos de crédito', path: '/admin/credits/types', icon: 'M4 5h16v14H4z M8 9h8 M8 13h5' }, { label: 'Tasas', path: '/admin/credits/rates', icon: 'M12 3v18 M17 7H9a3 3 0 0 0 0 6h6a3 3 0 0 1 0 6H6' }, { label: 'Cargos', path: '/admin/credits/charges', icon: 'M5 4h14v16H5z M8 8h8 M8 12h8 M8 16h5' }, { label: 'Simulador', path: '/admin/credits/simulator', icon: 'M4 19V5 M4 19h16 M8 15v-4 M12 15V7 M16 15v-7' }, { label: 'Comparación', path: '/admin/credits/comparison', icon: 'M5 5h5v14H5z M14 9h5v10h-5z' }] },
    { label: 'INVERSIONES', items: [{ label: 'Productos', path: '/admin/investments/products', icon: 'M4 7l8-4 8 4-8 4z M4 7v10l8 4 8-4V7' }, { label: 'Tasas', path: '/admin/investments/rates', icon: 'M12 3v18 M17 7H9a3 3 0 0 0 0 6h6a3 3 0 0 1 0 6' }, { label: 'Solicitudes', path: '/admin/investments/applications', icon: 'M6 3h9l3 3v15H6z M9 12h6 M9 16h6' }] },
    { label: 'SISTEMA', items: [{ label: 'Institución', path: '/admin/institution', icon: 'M4 21h16 M6 21V8l6-4 6 4v13 M9 12h1 M14 12h1 M9 16h1 M14 16h1' }] }
  ];
  initials(): string { return (this.institution()?.name || 'FinanSmart').split(' ').filter(Boolean).slice(0,2).map(part => part[0]).join('').toUpperCase(); }
}
