import { Component, ElementRef, HostListener, inject, output, signal } from '@angular/core';
import { AuthStateService } from '../../core/auth/services/auth-state.service';

@Component({
  selector: 'app-admin-topbar',
  template: `<header class="topbar"><button class="menu-button" type="button" aria-label="Abrir menú" (click)="menuClicked.emit()"><svg viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16" /></svg></button><div class="title"><small>Administración</small><strong>Panel de control</strong></div><div class="user-menu"><button class="user-button" type="button" [attr.aria-expanded]="isOpen()" aria-haspopup="menu" (click)="isOpen.set(!isOpen())"><span class="avatar">{{ initials() }}</span><span class="user-copy"><strong>{{ fullName() }}</strong><small>{{ role() }}</small></span><svg class="chevron" viewBox="0 0 24 24"><path d="m7 10 5 5 5-5" /></svg></button>@if (isOpen()) {<div class="dropdown" role="menu"><p>{{ authState.currentUser()?.email }}</p><hr><button type="button" role="menuitem" (click)="logout()">Cerrar sesión</button></div>}</div></header>`,
  styles: [`.topbar{position:sticky;top:0;z-index:15;display:flex;align-items:center;min-height:72px;padding:0 30px;border-bottom:1px solid var(--topbar-border);background:var(--topbar-bg);backdrop-filter:blur(10px)}.menu-button{display:grid;width:40px;height:40px;place-items:center;border:1px solid var(--brand-primary);border-radius:10px;background:var(--brand-primary);color:var(--primary-contrast);transition:.16s}.menu-button:hover{background:var(--brand-primary-hover)}.menu-button:active{background:var(--brand-primary-active);transform:translateY(1px)}.menu-button:focus-visible{outline:3px solid var(--brand-primary-hover);outline-offset:2px}.menu-button svg,.chevron{width:19px;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round}.title{display:grid;gap:1px;margin-left:14px}.title small{color:var(--text-muted);font-size:.7rem}.title strong{font-size:.9rem}.user-menu{position:relative;margin-left:auto}.user-button{display:flex;align-items:center;gap:9px;border:0;border-radius:12px;background:transparent;padding:5px 7px;color:var(--text);text-align:left}.user-button:hover{background:var(--surface-muted)}.avatar{display:grid;width:38px;height:38px;place-items:center;border-radius:50%;background:var(--brand-primary);color:var(--primary-contrast);font-size:.8rem;font-weight:800}.user-copy{display:grid;gap:2px}.user-copy strong{font-size:.84rem}.user-copy small{color:var(--text-muted);font-size:.7rem}.chevron{width:15px;color:var(--text-muted)}.dropdown{position:absolute;right:0;top:calc(100% + 10px);width:235px;padding:10px;border:1px solid var(--border);border-radius:12px;background:var(--surface);box-shadow:var(--shadow-md)}.dropdown p{margin:3px 5px 10px;overflow-wrap:anywhere;color:var(--text-muted);font-size:.76rem}.dropdown hr{border:0;border-top:1px solid var(--border)}.dropdown button{width:100%;border:0;border-radius:8px;background:transparent;padding:10px;text-align:left;color:var(--danger);font-weight:700}.dropdown button:hover{background:var(--surface-subtle)}@media(max-width:767px){.topbar{min-height:64px;padding:0 16px}.title small{display:none}.user-copy,.chevron{display:none}}`]
})
export class AdminTopbarComponent {
  private readonly elementRef = inject(ElementRef); readonly authState = inject(AuthStateService); readonly menuClicked = output<void>(); readonly isOpen = signal(false);
  @HostListener('document:click', ['$event']) onDocumentClick(event: Event) { if (!this.elementRef.nativeElement.contains(event.target)) this.isOpen.set(false); }
  @HostListener('document:keydown.escape') onEscape() { this.isOpen.set(false); }
  fullName(): string { const user = this.authState.currentUser(); return user ? `${user.firstName} ${user.lastName}`.trim() : 'Administrador'; }
  role(): string { return this.authState.currentUser()?.roles[0] === 'Admin' ? 'Administrador' : this.authState.currentUser()?.roles[0] || ''; }
  initials(): string { return this.fullName().split(' ').filter(Boolean).map(name => name[0]).join('').slice(0,2).toUpperCase() || 'A'; }
  logout(): void { this.isOpen.set(false); this.authState.logout().subscribe(); }
}
