import { Component, DestroyRef, computed, inject, signal } from '@angular/core'; import { HttpErrorResponse } from '@angular/common/http'; import { NonNullableFormBuilder, ReactiveFormsModule, ValidatorFn, Validators } from '@angular/forms'; import { takeUntilDestroyed } from '@angular/core/rxjs-interop'; import { PageHeaderComponent } from '../../../../shared/components/page-header/page-header.component'; import { LoadingSpinnerComponent } from '../../../../shared/components/loading-spinner/loading-spinner.component'; import { EmptyStateComponent } from '../../../../shared/components/empty-state/empty-state.component'; import { StatusBadgeComponent } from '../../../../shared/components/status-badge/status-badge.component'; import { StatCardComponent } from '../../../../shared/components/stat-card/stat-card.component'; import { InterestCalculationMethod, InterestPaymentFrequency, InvestmentProduct, InvestmentProductFormData } from './models/investment-product.model'; import { InvestmentProductService } from './services/investment-product.service';
const positive:ValidatorFn=c=>typeof c.value==='number'&&c.value>0?null:{positive:true}; const range=(a:string,b:string,n:string):ValidatorFn=>g=>{const x=g.get(a)?.value,y=g.get(b)?.value;return y!==null&&y!==''&&y<x?{[n]:true}:null;};
@Component({selector:'app-investment-products',imports:[ReactiveFormsModule,PageHeaderComponent,LoadingSpinnerComponent,EmptyStateComponent,StatusBadgeComponent,StatCardComponent],templateUrl:'./investment-products.component.html',styleUrl:'./investment-products.component.scss'})
export class InvestmentProductsComponent {
 private readonly destroyRef=inject(DestroyRef); private readonly fb=inject(NonNullableFormBuilder); private readonly service=inject(InvestmentProductService); private readonly moneyFormat=new Intl.NumberFormat('es-EC',{style:'currency',currency:'USD'});
 readonly products=signal<InvestmentProduct[]>([]); readonly loading=signal(true); readonly loadError=signal(false); readonly saving=signal(false); readonly modalOpen=signal(false); readonly editing=signal<InvestmentProduct|null>(null); readonly confirmation=signal<InvestmentProduct|null>(null); readonly feedback=signal(''); readonly feedbackType=signal<'success'|'error'>('success'); readonly methodFilter=signal<'all'|InterestCalculationMethod>('all'); readonly frequencyFilter=signal<'all'|InterestPaymentFrequency>('all'); readonly activeFilter=signal<'all'|'active'|'inactive'>('all');
 readonly form=this.fb.group({name:['',Validators.required],description:[''],minimumAmount:[0,[Validators.required,positive]],maximumAmount:[null as number|null],minimumTermDays:[0,[Validators.required,positive,Validators.pattern(/^[0-9]+$/)]],maximumTermDays:[null as number|null],interestCalculationMethod:['Simple' as InterestCalculationMethod,Validators.required],interestPaymentFrequency:['AtMaturity' as InterestPaymentFrequency,Validators.required],isActive:[true]},{validators:[range('minimumAmount','maximumAmount','amountRange'),range('minimumTermDays','maximumTermDays','termRange')]});
 readonly filtered=computed(()=>this.products().filter(x=>(this.methodFilter()==='all'||x.interestCalculationMethod===this.methodFilter())&&(this.frequencyFilter()==='all'||x.interestPaymentFrequency===this.frequencyFilter())&&(this.activeFilter()==='all'||(this.activeFilter()==='active'?x.isActive:!x.isActive))));
 readonly activeCount=computed(()=>this.products().filter(x=>x.isActive).length); readonly simpleCount=computed(()=>this.products().filter(x=>x.interestCalculationMethod==='Simple').length); readonly compoundCount=computed(()=>this.products().filter(x=>x.interestCalculationMethod==='Compound').length);
 constructor(){this.load();}
 load(){this.loading.set(true);this.loadError.set(false);this.service.getAll().pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:x=>{this.products.set(x);this.loading.set(false);},error:()=>{this.loadError.set(true);this.loading.set(false);}});}
 openCreate(){this.editing.set(null);this.form.reset({name:'',description:'',minimumAmount:0,maximumAmount:null,minimumTermDays:0,maximumTermDays:null,interestCalculationMethod:'Simple',interestPaymentFrequency:'AtMaturity',isActive:true});this.modalOpen.set(true);}
 openEdit(x:InvestmentProduct){this.editing.set(x);this.form.reset({...x,description:x.description??''});this.modalOpen.set(true);}
 close(){if(!this.saving())this.modalOpen.set(false);} closeConfirm(){if(!this.saving())this.confirmation.set(null);}
 save(){if(this.form.invalid||this.saving()){this.form.markAllAsTouched();return;}this.saving.set(true);const r=this.form.getRawValue();const data:InvestmentProductFormData={...r,description:r.description.trim()||null,maximumAmount:r.maximumAmount||null,maximumTermDays:r.maximumTermDays||null};const e=this.editing();(e?this.service.update(e.id,data):this.service.create(data)).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:()=>{this.saving.set(false);this.modalOpen.set(false);this.notice(e?'Producto de inversión actualizado correctamente.':'Producto de inversión creado correctamente.','success');this.load();},error:x=>{this.saving.set(false);this.notice(this.errorMessage(x),'error');}});}
 deactivate(){const x=this.confirmation();if(!x||this.saving())return;this.saving.set(true);this.service.delete(x.id).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:()=>{this.saving.set(false);this.confirmation.set(null);this.notice('Producto de inversión desactivado correctamente.','success');this.load();},error:x=>{this.saving.set(false);this.notice(this.errorMessage(x),'error');}});}
 reactivate(x:InvestmentProduct){if(this.saving())return;this.saving.set(true);const {id,createdAt,updatedAt,...data}=x;this.service.update(id,{...data,isActive:true}).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:()=>{this.saving.set(false);this.notice('Producto de inversión reactivado correctamente.','success');this.load();},error:e=>{this.saving.set(false);this.notice(this.errorMessage(e),'error');}});}
 money(x:number){return this.moneyFormat.format(x);} amount(x:InvestmentProduct){return x.maximumAmount===null?`Desde ${this.money(x.minimumAmount)}`:`${this.money(x.minimumAmount)} - ${this.money(x.maximumAmount)}`;} term(x:InvestmentProduct){return x.maximumTermDays===null?`Desde ${x.minimumTermDays} días`:`${x.minimumTermDays} - ${x.maximumTermDays} días`;} method(x:InterestCalculationMethod){return x==='Simple'?'Interés simple':'Interés compuesto';} frequency(x:InterestPaymentFrequency){return ({AtMaturity:'Al vencimiento',Monthly:'Mensual',Quarterly:'Trimestral',SemiAnnual:'Semestral',Upfront:'Anticipado'})[x];} methodHelp(){return this.form.controls.interestCalculationMethod.value==='Simple'?'Los intereses se calculan sobre el capital inicial.':'Los intereses se acumulan sobre el capital y los intereses generados.';} frequencyHelp(){return ({AtMaturity:'Los intereses se pagan al finalizar la inversión.',Monthly:'Los intereses se pagan periódicamente cada mes.',Quarterly:'Los intereses se pagan cada tres meses.',SemiAnnual:'Los intereses se pagan cada seis meses.',Upfront:'Los intereses se entregan al inicio de la operación.'})[this.form.controls.interestPaymentFrequency.value];} clearFilters(){this.methodFilter.set('all');this.frequencyFilter.set('all');this.activeFilter.set('all');} setFilter(k:string,e:Event){const v=(e.target as HTMLSelectElement).value;if(k==='method')this.methodFilter.set(v as 'all'|InterestCalculationMethod);if(k==='frequency')this.frequencyFilter.set(v as 'all'|InterestPaymentFrequency);if(k==='active')this.activeFilter.set(v as 'all'|'active'|'inactive');} private notice(m:string,t:'success'|'error'){this.feedback.set(m);this.feedbackType.set(t);} private errorMessage(e:HttpErrorResponse){if(e.status===0)return'No se pudo conectar con el servidor.';if(e.status===404)return'El producto de inversión ya no existe.';if(e.status===409)return'Ya existe un producto activo con ese nombre.';if(e.status===400)return'Revisa la configuración del producto.';return'Ocurrió un error al procesar la solicitud.';}
}
